# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='Doctor', max_length=25)),
                ('lastname', models.CharField(default='Nurse', max_length=25)),
                ('email', models.EmailField(default='doctor@placeholder.com', max_length=254)),
                ('specialty', models.CharField(default='Proctology', max_length=50)),
                ('photo', models.ImageField(max_length=255, null=True, upload_to='/Users/robcardy/Programming/PycharmProjects/Lyff/lyff-server/server/images')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.IntegerField(default=1)),
                ('patient', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('firstname', models.CharField(default='Testy', max_length=25)),
                ('lastname', models.CharField(default='Tester', max_length=25)),
                ('email', models.EmailField(default='tester@placeholder.com', max_length=254)),
                ('password', models.CharField(default='fakepassword', max_length=40)),
                ('phone', models.CharField(default='5191231234', max_length=20)),
                ('age', models.IntegerField(default=-1)),
                ('weight', models.IntegerField(default=-1)),
                ('height', models.IntegerField(default=-1)),
                ('healthcard', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('photo', models.ImageField(max_length=255, null=True, upload_to='/Users/robcardy/Programming/PycharmProjects/Lyff/lyff-server/server/images')),
            ],
        ),
    ]
