# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='doctor@placeholder.com', max_length=254),
        ),
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(to='server.Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='healthcard',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
